# Generated by Django 5.1 on 2024-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusInsight', '0002_exam_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/'),
        ),
    ]
