# Generated by Django 5.1 on 2024-08-19 09:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusInsight', '0003_exam_docx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 19, 9, 22, 50, 636436, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
